---
title: "Single Data Set Analysis"
author: "Alex"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(openxlsx)
library(dplyr)
library(tidyr)
library(purrr)
library(ModelMetrics)
library(ggplot2)
library(stringr)
```

```{r Import Data}
inputdata <- read_xlsx("inputdata.xlsx", sheet = "AZD") # "AZD") "Dasatinib") "BMS") "HG6-64-1"

randomizer = "range.randomizer_2.R"
x <- pull(inputdata,1)
y <- pull(inputdata,2)
ActiveName <- as.vector(colnames(inputdata[,2]))

testdata <- as.data.frame(cbind(x,y))
```

```{r Biphasic Model Regression Calculations}
for (iterations in c(1:1)){
{
  #inputs
  biphasic.function <- function(x) {1-a*x/(b+x) -(1-a)*x/(c+x)}
  deriv.fuction <- function(x) {-c/(c + x)^2 + a*(-b/(b + x)^2 + c/(c + x)^2)}
  activefunction <- biphasic.function
  z <- c(0:5)  #iterations
  s <- 10       #Number of subdivisions to do during regression
  a <- c(0,1)  #F1 term
  b <- c(0,10) #Kd1
  c <- c(0,10) #Kd2
  d <- NA #currently the offset for when Imax is reached
}
source(file = "dirtyregression.R", local = TRUE)

{#outputs
  all.runs <- distinct(all.runs)
  biphasic.results <- all.runs[order(all.runs$RMSE), ] [1,]
  a <- as.numeric(biphasic.results$a)
  b <- as.numeric(biphasic.results$b)
  c <- as.numeric(biphasic.results$c)
  RMSE <- as.numeric(biphasic.results$RMSE)
}
{#Calculate IC50[]
  tempterm <- 0.5*(2*a*b - b - 2*a*c + c + sqrt((-2*a*b + b + 2*a*c - c)^2 + 4*b*c))
  tempterm2 <- 0.5*(2*a*b - b - 2*a*c + c - sqrt((-2*a*b + b + 2*a*c - c)^2 + 4*b*c))
  IC50 <- max(tempterm, tempterm2)
}

n <- max(length(x), length(y), length(tempvector))
length(x) <- n                      
length(y) <- n
length(tempvector) <- n

tempdata <- tempvector
tempdata <- cbind(tempdata, x)
tempdata <- as.data.frame(cbind(tempdata, y))
tempterm <- paste("~/Desktop/plots/", ActiveName, "_Data.csv", sep = "")

write.csv(tempdata, file = tempterm)

#Graph Function
temptext <- paste(ActiveName, "Biphasic Minimalization", sep = " ")
biphasic.results.text <- paste("BiphasicModel: ", "F1=", round(a, digits = 4) , ", Kd1=", round(b, digits = 4), ", Kd2=", round(c, digits = 4), " Offset=", d, ", RMSE=", round(RMSE, digits = 4), ", IC50=", round(IC50, digits = 4), sep = "")

x <- pull(inputdata,1)
y <- pull(inputdata,2)
testdata <- as.data.frame(cbind(x,y))

tempterm <- max(max(x), IC50)
ggplot(data = testdata, aes(x = x, y = y)) +
  geom_point()+
  geom_function(fun = biphasic.function)+ 
  scale_x_continuous(trans = "log10")+
  labs(title = temptext, x = "lnCONC", y = "Relative Viability") +
  annotate(geom = "text", x = 1 ,  y=1.5, label = str_wrap(biphasic.results.text, 50))+
  ylim(0, 1.5)+
  ggsave(plot = last_plot(), filename = paste(ActiveName, "Biphasic_Minimalization_Plot.png", sep = ""), width = 10, height = 10, device = NULL)

#Report the Results
all_results <- read_xlsx("all_results.xlsx")
output_results <- c(ActiveName, "Script", a, b, c, RMSE, IC50)
all_results <- rbind(all_results, output_results)
write.csv(all_results, file = "all_results.csv")
write.xlsx(all_results, file = "all_results.xlsx")
}
```


Slope Calculations
```{r Slope Calculations}
x <- pull(inputdata, 1)
logx <- log10(x)
y <- pull(inputdata, 2)

testdata <- as.data.frame(cbind(logx,y))

slope_report <- t(as.data.frame(c(0,0,0,0,0)))
colnames(slope_report) <- c("i", "x","logx", "y", "slope")

tempvector <- c()
tempterm <- seq(from = 1, to = length(x), by = 1)

for(i in tempterm){
  if (i == min(tempterm)){a <- i} else {a <- i - 1}
  if (i == max(tempterm)){b <- i} else {b <- i + 1}

  i
  #a / left side
  tempdata <- testdata[a:i,]
  low_slope <- (tempdata[2,2]-tempdata[1,2])/(tempdata[2,1]-tempdata[1,1])
  tempdata <- testdata[i:b,]
  high_slope <- (tempdata[2,2]-tempdata[1,2])/(tempdata[2,1]-tempdata[1,1])
  if (a == i){low_slope <- high_slope}else{}
  if (b == i){high_slope <- low_slope}else{}
  
  slope <- (high_slope+low_slope)/2
  
  tempvector <- c(i, x[i], logx[i], y[i], slope)               
  slope_report <- rbind(slope_report, tempvector)
  print(paste(a,i,b, sep = ","))  
}
slope_report <- as.data.frame(slope_report)

ggplot(data = slope_report, aes(x = x, y = slope))+
  geom_line()+
  scale_x_continuous(trans = "log10") + 
  labs(title = paste(ActiveName,"Slopes", sep = " "), x = "lnCONC", y = "Slope")+
  ggsave(plot = last_plot(), filename = paste(ActiveName, "_Slope_Plot.png", sep = ""), width = 10, height = 10, device = NULL)
```


```{r}
temptext <- paste(ActiveName, "Biphasic Minimalization", sep = " ")
biphasic.results.text <- paste("BiphasicModel: ", "F1=", round(a, digits = 4) , ", Kd1=", round(b, digits = 4), ", Kd2=", round(c, digits = 4), " Offset=", d, ", RMSE=", round(RMSE, digits = 4), ", IC50=", round(IC50, digits = 4), sep = "")

x <- pull(inputdata,1)
y <- pull(inputdata,2)
testdata <- as.data.frame(cbind(x,y))

tempterm <- max(max(x), IC50)

  for (i in (1:20)){
  print(paste("biphasic.function.", i, " <- function(x) {1-as.numeric(results$a[",i,"])*x/(as.numeric(results$b[",i,"])+x)-(1-as.numeric(results$a[",i,"]))*x/(as.numeric(results$c[",i,"])+x}+", sep = ""))
  }

biphasic.function.1 <- function(x){1-as.numeric(results$a[1])*x/(as.numeric(results$b[1])+x)-(1-as.numeric(results$a[1]))*x/(as.numeric(results$c[1])+x)}
biphasic.function.2<- function(x){1-as.numeric(results$a[2])*x/(as.numeric(results$b[2])+x)-(1-as.numeric(results$a[2]))*x/(as.numeric(results$c[2])+x)}
biphasic.function.3<- function(x){1-as.numeric(results$a[3])*x/(as.numeric(results$b[3])+x)-(1-as.numeric(results$a[3]))*x/(as.numeric(results$c[3])+x)}
biphasic.function.4<- function(x){1-as.numeric(results$a[4])*x/(as.numeric(results$b[4])+x)-(1-as.numeric(results$a[4]))*x/(as.numeric(results$c[4])+x)}
biphasic.function.5<- function(x){1-as.numeric(results$a[5])*x/(as.numeric(results$b[5])+x)-(1-as.numeric(results$a[5]))*x/(as.numeric(results$c[5])+x)}
biphasic.function.6<- function(x){1-as.numeric(results$a[6])*x/(as.numeric(results$b[6])+x)-(1-as.numeric(results$a[6]))*x/(as.numeric(results$c[6])+x)}
biphasic.function.7<- function(x){1-as.numeric(results$a[7])*x/(as.numeric(results$b[7])+x)-(1-as.numeric(results$a[7]))*x/(as.numeric(results$c[7])+x)}
biphasic.function.8<- function(x){1-as.numeric(results$a[8])*x/(as.numeric(results$b[8])+x)-(1-as.numeric(results$a[8]))*x/(as.numeric(results$c[8])+x)}
biphasic.function.9<- function(x){1-as.numeric(results$a[9])*x/(as.numeric(results$b[9])+x)-(1-as.numeric(results$a[9]))*x/(as.numeric(results$c[9])+x)}
biphasic.function.10<- function(x){1-as.numeric(results$a[10])*x/(as.numeric(results$b[10])+x)-(1-as.numeric(results$a[10]))*x/(as.numeric(results$c[10])+x)}
biphasic.function.11<- function(x){1-as.numeric(results$a[11])*x/(as.numeric(results$b[11])+x)-(1-as.numeric(results$a[11]))*x/(as.numeric(results$c[11])+x)}
biphasic.function.12<- function(x){1-as.numeric(results$a[12])*x/(as.numeric(results$b[12])+x)-(1-as.numeric(results$a[12]))*x/(as.numeric(results$c[12])+x)}
biphasic.function.13<- function(x){1-as.numeric(results$a[13])*x/(as.numeric(results$b[13])+x)-(1-as.numeric(results$a[13]))*x/(as.numeric(results$c[13])+x)}
biphasic.function.14<- function(x){1-as.numeric(results$a[14])*x/(as.numeric(results$b[14])+x)-(1-as.numeric(results$a[14]))*x/(as.numeric(results$c[14])+x)}
biphasic.function.15<- function(x){1-as.numeric(results$a[15])*x/(as.numeric(results$b[15])+x)-(1-as.numeric(results$a[15]))*x/(as.numeric(results$c[15])+x)}
biphasic.function.16<- function(x){1-as.numeric(results$a[16])*x/(as.numeric(results$b[16])+x)-(1-as.numeric(results$a[16]))*x/(as.numeric(results$c[16])+x)}
biphasic.function.17<- function(x){1-as.numeric(results$a[17])*x/(as.numeric(results$b[17])+x)-(1-as.numeric(results$a[17]))*x/(as.numeric(results$c[17])+x)}
biphasic.function.18<- function(x){1-as.numeric(results$a[18])*x/(as.numeric(results$b[18])+x)-(1-as.numeric(results$a[18]))*x/(as.numeric(results$c[18])+x)}
biphasic.function.19<- function(x){1-as.numeric(results$a[19])*x/(as.numeric(results$b[19])+x)-(1-as.numeric(results$a[19]))*x/(as.numeric(results$c[19])+x)}
biphasic.function.20<- function(x){1-as.numeric(results$a[20])*x/(as.numeric(results$b[20])+x)-(1-as.numeric(results$a[20]))*x/(as.numeric(results$c[20])+x)}


ggplot(data = testdata, aes(x = x, y = y)) +
  geom_point() +
  geom_function(fun = biphasic.function)+
  geom_function(fun = biphasic.function.1)+
  geom_function(fun = biphasic.function.2)+
  geom_function(fun = biphasic.function.3)+
  geom_function(fun = biphasic.function.4)+
  geom_function(fun = biphasic.function.5)+
  geom_function(fun = biphasic.function.6)+
  geom_function(fun = biphasic.function.7)+
  geom_function(fun = biphasic.function.8)+
  geom_function(fun = biphasic.function.9)+
  geom_function(fun = biphasic.function.10)+
  geom_function(fun = biphasic.function.11)+
  geom_function(fun = biphasic.function.12)+
  geom_function(fun = biphasic.function.13)+
  geom_function(fun = biphasic.function.14)+
  geom_function(fun = biphasic.function.15)+
  geom_function(fun = biphasic.function.16)+
  geom_function(fun = biphasic.function.17)+
  scale_x_continuous(trans = "log10")+
  labs(title = temptext, x = "lnCONC", y = "Relative Viability") +
  annotate(geom = "text", x = 1 ,  y=1.5, label = str_wrap(biphasic.results.text, 50))+
  ylim(0, 1.5)+
  ggsave(plot = last_plot(), filename = paste(ActiveName, "Biphasic_Minimalization_Plot.png", sep = ""), width = 10, height = 10, device = NULL)


```

