---
title: "Untitled"
author: "Alex"
date: "5/30/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Setup:
library(tidyr)
library(lattice)
library(reshape2)
library(readxl)
library(ggplot2)
library(data.table)
library(dplyr)
library(deSolve)
library(glue)
library(CARRoT)
library(caret)
library(nlme)
library(ggplot2)
library(broom)
#Repeat Libraries to reduce error
library(reshape2)
library(readxl)
library(ggplot2)
library(data.table)
library(dplyr)
library(deSolve)
library(glue)
library(CARRoT)
library(caret)
library(nlme)
library(ggplot2)
library(broom)
library(ModelMetrics)
library(aomisc)
library(drmdel)
library(drc)
library(nlme)

inputdata <- read.csv("equation.test.data.csv", nrows = 10)
```

```{r, echo=FALSE}
#Import Data - Change Name for different tables of Cell/Drug Combos 
equation_test_data <- inputdata$CELL_LINE_NAME
equation_test_data <- cbind(equation_test_data, inputdata$DRUG_ID)
colnames(equation_test_data) <- c("CELL_LINE_NAME","DRUG_ID")
equation_test_data <- cbind(equation_test_data, inputdata[1:10,13:19])
equation_test_data[equation_test_data == "NA"] <- 0

ActiveName <- paste(equation_test_data$CELL_LINE_NAME[1],equation_test_data$DRUG_ID[2], sep="_")

# Data Prep
x <- -1*equation_test_data$lnCONC
y <- equation_test_data$RELATIVE_VIABILITY

#Zeroing & Normalizing by subtraction of smallest term
tempterm <- min(x)
x <- x-tempterm
if (min(y) <= 0) {
  tempterm <- min(y)
  y <- y-tempterm} else {y <- y}

testdata <- as.data.frame(x)
testdata <- cbind(testdata, y)
testdata[] <- round(testdata[], digits = 3)
testdata[testdata == "Inf"] <- 10
testdata[testdata == "-Inf"] <- -10
testdata <- as.data.frame(testdata)

```

```{r}
#Biphasic Model Regression Calculations
#inputs
activefunction <- function(x) {a*x/(b+x)+(1-a)*x/(c+x)+d}
offset.activefunction <- function(x) {a*(x-d)/(b+(x-d))+(1-a)*(x-d)/(c+(x-d))}

# a and b coded to never equal 0
x <- testdata$x
y <- testdata$y
z <- c(0:10)  #iterations
s <- 6        #Number of subdivisions to do during regression
a <- c(-1,1)  #F1 term
b <- c(-1,10) #Kd1
c <- c(-1,10) #Kd2
d <- c(-1,10) #currently the offset for when Imax is reached

source(file = "dirtyregression.R", local = TRUE)

#outputs
results <- results[order(results$RMSEscore), ] [1,]
a <- as.numeric(results$a)
b <- as.numeric(results$b)
c <- as.numeric(results$c)
d <- as.numeric(results$d)
RMSE <- as.numeric(results$RMSEscore)

#Graph Function
temptext <- paste(ActiveName, "Dirty Biphasic Regression", sep = " ")
temptext2 <- paste("a = ", a, ", b = ", b, ", c = ", c, ", d = ", d, ", RMSE ", RMSE, sep = "")

ggplot(data = testdata, aes(x = x, y = y)) +
  geom_point()+
  geom_function(fun = offset.activefunction)+ 
  labs(title = temptext, subtitle = temptext2, x = "LnCONC", y = "Relative Viability") +
  ylim(0, 1.5)+
  ggsave(plot = last_plot(), filename = "Dirty_Biphasic_RegressionPlot.png", width = 4, height = 4, device = NULL)

#Calculate IC50
IC50 <- 0.5*(2*a*b - b - 2*a*c + c + sqrt(((2*a - 1)*b - 2*a*c + c)^2 + 4*b*c))+d

#Construct Results CSV
dirtyregressionresults <- as.data.frame(c())
tempvector <- c(ActiveName, "Biphasic Model", a, b, c, d, RMSEscore, IC50)
dirtyregressionresults <- rbind(dirtyregressionresults, tempvector)
colnames(dirtyregressionresults) <- c("ActiveName", "Biphasic Model", "a", "b", "c", "d", "RMSEscore", "IC50")

```

```{r}
#Gompertz Model Regression Calculations
      #inputsoffset.
      activefunction <- function(x) {c+(a-c)*exp(-exp(-b*(x-d)))}
      offset.activefunction <- function(x) {c+(a-c)*exp(-exp(-b*(x-d)))}
      
      # a and b coded to never equal 0
      x <- testdata$x
      y <- testdata$y
      z <- c(0:10)  #iterations
      s <- 6        #Number of subdivisions to do during regression
      a <- c(-1,1)  # gomp d
      b <- c(-1,1)  # gomp b
      c <- c(-1,1)  # gomp c
      d <- c(-1,1)  # gomp e
      
      source(file = "dirtyregression.R", local = TRUE)
      
      #outputs
      results <- results[order(results$RMSEscore), ] [1,]
      a <- as.numeric(results$a)
      b <- as.numeric(results$b)
      c <- as.numeric(results$c)
      d <- as.numeric(results$d)
      RMSE <- as.numeric(results$RMSEscore)
      
      #Graph Function
      temptext <- paste(ActiveName, "Dirty Regression", sep = " ")
      temptext2 <- paste("a = ", a, ", b = ", b, ", c = ", c, ", d = ", d, ", RMSE ", RMSE, sep = "")
      
      ggplot(data = testdata, aes(x = x, y = y)) +
        geom_point()+
        geom_function(fun = offset.activefunction)+ 
        labs(title = temptext, subtitle = temptext2, x = "LnCONC", y = "Relative Viability") +
        ylim(0, 1.5)+
        ggsave(plot = last_plot(), filename = "Dirty_Gompertz_RegressionPlot.png", width = 4, height = 4, device = NULL)

      
      #Calculate IC50
      IC50 <- (b*d - log(log(-1*(2*c - 2*a)/(1 - 2*c))))/b

      #Append Results CSV
      tempvector <- c(ActiveName, "Gompertz Model", a, b, c, d, RMSEscore, IC50)
      dirtyregressionresults <- rbind(dirtyregressionresults, tempvector)
```


