---
title: "Gomp Funct Work"
author: "Alex"
date: "5/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Setup:
library(tidyr)
library(lattice)
library(reshape2)
library(readxl)
library(ggplot2)
library(data.table)
library(dplyr)
library(deSolve)
library(glue)
library(CARRoT)
library(caret)
library(nlme)
library(ggplot2)
library(broom)
#Repeat Libraries to reduce error
library(reshape2)
library(readxl)
library(ggplot2)
library(data.table)
library(dplyr)
library(deSolve)
library(glue)
library(CARRoT)
library(caret)
library(nlme)
library(ggplot2)
library(broom)

library(ModelMetrics)
library(aomisc)
library(drmdel)
library(drc)
library(nlme)

inputdata <- read.csv("equation.test.data.csv", nrows = 10)
```

```{r, echo=FALSE}
#Import Data - Change Name for different tables of Cell/Drug Combos 
equation_test_data <- inputdata$CELL_LINE_NAME
equation_test_data <- cbind(equation_test_data, inputdata$DRUG_ID)
colnames(equation_test_data) <- c("CELL_LINE_NAME","DRUG_ID")
equation_test_data <- cbind(equation_test_data, inputdata[1:10,13:19])
equation_test_data[equation_test_data == "NA"] <- 0

ActiveName <- paste(equation_test_data$CELL_LINE_NAME[1],equation_test_data$DRUG_ID[2], sep="_")

# Data Prep
x <- -1*equation_test_data$lnCONC
y <- equation_test_data$RELATIVE_VIABILITY

#Zeroing & Normalizing by subtraction of smallest term
tempterm <- min(x)
x <- x-tempterm
if (min(y) <= 0) {
  tempterm <- min(y)
  y <- y-tempterm} else {y <- y}

testdata <- as.data.frame(x)
testdata <- cbind(testdata, y)
testdata[] <- round(testdata[], digits = 3)
testdata[testdata == "Inf"] <- 10
testdata[testdata == "-Inf"] <- -10
testdata <- as.data.frame(testdata)

# Check Plot for Errors 
plot(testdata$x, testdata$y, xlab = "LnCONC", ylab = "Relative Viability", main = paste(ActiveName, "BasePlot 1", sep = ""))

# Determine Offset for real-values
offset <- max(equation_test_data$lnCONC)

#Set Generic Weighting; favor values closer to ".5"
generic_weighting <- .3 + (1-.3)*exp(-10*(testdata$y-.5)^2)
testdata$generic_weighting <- generic_weighting
```

```{r}
testdata <- testdata
#for (i in testdata$y){
#  if (i <= .08){  
#    if (i != 0){
#      testdata <- subset(testdata, testdata$y != i)
#      } else (i <- i) 
#  } else (i <- i)
#}

testdata$x <- testdata$x - min(testdata$x)

activefunction <- function(x) {c+(a-c)*((exp(-exp(b*(x-d)))))}

x <- testdata$x
y <- testdata$y

Iterations <- c(0:10)
#Inital Ranges---
a <- c(-5,1)
b <- c(-1,10)
c <- c(-10,10)
d <- c(-1,10)

for (z in Iterations) {

tempvector <- a
if (tempvector[1] == tempvector[2] && tempvector[1] == 0)
  {tempvector <- c(-1,1)} else {tempvector <- tempvector}
if (tempvector[1] == tempvector[2]){
  tempvector <- c(.9*tempvector[1], 1.1*tempvector[1])
  } else {tempvector <- tempvector}
tempvector <- tempvector[order(tempvector)]
subset <- ((tempvector[2]-tempvector[1])/4)
range <- seq(from = tempvector[1], to = tempvector[2], by = subset)
#a can not equal 0
a <- range[range != 0]

tempvector <- b
if (tempvector[1] == tempvector[2] && tempvector[1] == 0)
  {tempvector <- c(-1,1)} else {tempvector <- tempvector}
if (tempvector[1] == tempvector[2]){
  tempvector <- c(.9*tempvector[1], 1.1*tempvector[1])
  } else {tempvector <- tempvector}
tempvector <- tempvector[order(tempvector)]
subset <- ((tempvector[2]-tempvector[1])/4)
range <- seq(from = tempvector[1], to = tempvector[2], by = subset)
b <- range
#b can not equal 0
b <- range[range != 0]

tempvector <- c
if (tempvector[1] == tempvector[2] && tempvector[1] == 0)
  {tempvector <- c(-1,1)} else {tempvector <- tempvector}
if (tempvector[1] == tempvector[2]){
  tempvector <- c(.9*tempvector[1], 1.1*tempvector[1])
  } else {tempvector <- tempvector}
tempvector <- tempvector[order(tempvector)]
subset <- ((tempvector[2]-tempvector[1])/4)
range <- seq(from = tempvector[1], to = tempvector[2], by = subset)
c <- range

tempvector <- d
if (tempvector[1] == tempvector[2] && tempvector[1] == 0)
  {tempvector <- c(-1,1)} else {tempvector <- tempvector}
if (tempvector[1] == tempvector[2]){
  tempvector <- c(.9*tempvector[1], 1.1*tempvector[1])
  } else {tempvector <- tempvector}
tempvector <- tempvector[order(tempvector)]
subset <- ((tempvector[2]-tempvector[1])/4)
range <- seq(from = tempvector[1], to = tempvector[2], by = subset)
d <- range
d <- range[range != 0]

tempvector <- c()
results <- transpose(as.data.frame(1:6))
colnames(results) <- c("a","b","c","d","RMSEscore","Iterations")
for (i in a){
  for (j in b){
    for (k in c){
      for (l in d){
        predict_y <- c()
        predict_y <- k+(i-k)*((exp(-exp(j*(x-l)))))
        RMSEscore <- RMSE(predict_y, testdata$y)
        tempvector <- c(i, j, k, l, RMSEscore, z)
        results <- rbind(results, tempvector)
       }
    }
  }
}

results <- results[order(results$RMSEscore), ] [1:2,]
a <- as.vector(results$a)
b <- as.vector(results$b)
c <- as.vector(results$c)
d <- as.vector(results$d)
RMSE <- as.vector(results$RMSEscore)

}
results <- results[order(results$RMSEscore), ] [1,]
a <- as.numeric(results$a)
b <- as.numeric(results$b)
c <- as.numeric(results$c)
d <- as.numeric(results$d)
RMSE <- as.numeric(results$RMSEscore)

#Graph Functionc <- c(0,10)
  temptext <- paste(ActiveName, "Dirty Regression", sep = " ")
  temptext2 <- paste("a = ", a, ", b = ", b, ", c = ", c, ", d = ", d, ", RMSE ", RMSE, sep = "")
  ggplot(data = testdata, aes(x = x, y = y)) +
    geom_point()+
    geom_function(fun = function(x){c+(a-c)*((exp(-exp(b*(x-d)))))})+
    labs(title = temptext, subtitle = temptext2, x = "LnCONC", y = "Relative Viability") +
    ylim(0, 1.5)+
    ggsave(plot = last_plot(), filename = "GompRegressionPlot.png", width = 4, height = 4, device = NULL)

```